algorandfoundation/algokit-utils-ts

docs/code/modules/index.md
src/app-deploy.spec.ts
src/app-deploy.ts

[Strip comments in TypeScript library
](https://dev.azure.com/makerxstudio/AlgoKit%20(Algorand%20Foundation)/_workitems/edit/125)
Remove comments from tealCode before deployment

strip comments from tealCode

---

docs/code/classes/types_app_client.ApplicationClient.md
docs/code/interfaces/types_app_client.AppClientCallABIArgs.md
docs/code/interfaces/types_app_client.AppClientCallCoreParams.md
docs/code/interfaces/types_app_client.AppClientCompilationParams.md
docs/code/interfaces/types_app_client.AppClientDeployCallInterfaceParams.md
docs/code/interfaces/types_app_client.AppClientDeployCoreParams.md
docs/code/interfaces/types_app_client.AppClientDeployParams.md
docs/code/interfaces/types_app_client.AppSourceMaps.md
docs/code/interfaces/types_app_client.FundAppAccountParams.md
docs/code/interfaces/types_app_client.ResolveAppById.md
docs/code/interfaces/types_app_client.SourceMapExport.md
docs/code/modules/types_app_client.md
src/types/app-client.spec.ts
src/types/app-client.ts

BREAKING CHANGE: There isa new `resolveBy` required property when creating an appClient and `indexer` and `existingDeployments` are now collapsed into `findExistingUsing`

fix(application-client): Make the getAppClient parameters much more intuitive to consume

---

docs/code/classes/types_app_client.ApplicationClient.md
docs/code/enums/types_app_spec.AVMType.md
docs/code/interfaces/types_app_spec.AppSources.md
docs/code/interfaces/types_app_spec.AppSpec.md
docs/code/interfaces/types_app_spec.CallConfig.md
docs/code/interfaces/types_app_spec.DeclaredSchemaValueSpec.md
docs/code/interfaces/types_app_spec.DefaultArgument.md
docs/code/interfaces/types_app_spec.Hint.md
docs/code/interfaces/types_app_spec.ReservedSchemaValueSpec.md
docs/code/interfaces/types_app_spec.Schema.md
docs/code/interfaces/types_app_spec.SchemaSpec.md
docs/code/interfaces/types_app_spec.StateSchemaSpec.md
docs/code/interfaces/types_app_spec.Struct.md
docs/code/modules/index.md
docs/code/modules/types_app_spec.md
src/app-client.ts
src/app.ts
src/types/app-client.ts
src/types/app-spec.ts

BREAKING CHANGE: The following deprecated methods have been removed: `getApplicationClient`, `getAppByIndex`, `appClient.getBoxValuesAsABIType`, `getABISignature`

chore: Removing deprecated methods given we are about to release a major version bump

---

docs/code/modules/index.md
src/transaction.spec.ts
src/transaction.ts

https://dev.azure.com/MakerXStudio/AlgoKit%20(Algorand%20Foundation)/_workitems/edit/430
Retry pending transaction information when the call returns a httpClient error

Pending transaction 404

---

docs/code/classes/types_app_client.ApplicationClient.md
docs/code/interfaces/types_app_client.AppClientCallABIArgs.md
docs/code/interfaces/types_app_client.AppClientCallCoreParams.md
docs/code/interfaces/types_app_client.AppClientCompilationParams.md
docs/code/interfaces/types_app_client.AppClientDeployCallInterfaceParams.md
docs/code/interfaces/types_app_client.AppClientDeployCoreParams.md
docs/code/interfaces/types_app_client.AppClientDeployParams.md
docs/code/interfaces/types_app_client.AppSourceMaps.md
docs/code/interfaces/types_app_client.FundAppAccountParams.md
docs/code/interfaces/types_app_client.ResolveAppById.md
docs/code/interfaces/types_app_client.ResolveAppByIdBase.md
docs/code/interfaces/types_app_client.SourceMapExport.md
docs/code/modules/index.md
docs/code/modules/types_app_client.md
src/app-client.ts
src/types/app-client.ts

https://dev.azure.com/makerxstudio/AlgoKit%20(Algorand%20Foundation)/_backlogs/backlog/AlgoKit%20(Algorand%20Foundation)%20Team/Features/?showParents=true&workitem=714

fix: increase discoverability of algokit resolve by id and name methods

---

docs/code/classes/testing.TestLogger.md
docs/code/classes/types_logic_error.LogicError.md
docs/code/interfaces/types_testing.AlgorandFixture.md
docs/code/modules/index.md
docs/code/modules/testing.md
package-lock.json
package.json

This fixes a bug when deploying code to e.g. AWS Lambda and the node_modules is optimised such that cross-fetch isn't able to be imported
Also updated packages to latest versions.

fix: Added cross-fetch as an explicit dependency to not rely on it coming from algosdk

---

.github/workflows/pr.yml
docs/code/classes/testing.TestLogger.md
docs/code/classes/types_logic_error.LogicError.md
docs/code/interfaces/types_testing.AlgorandFixture.md
docs/code/modules/index.md
docs/code/modules/testing.md

- Fixing merged conflicting docs, attempt 2 
- Adjusting CI not to ignore changes in the .md files

docs: updating missing docs rev2

---

.github/workflows/pr.yml
.github/workflows/release.yml
package-lock.json
package.json

Update the following dependencies:
- conventional-changelog-conventionalcommits
- typedoc
- semantic-release
- typescript
Update the minimum desired node version to 18.0

deps: Dependency updates

---

package.json

BREAKING CHANGE: adding explicit types export into package json for correct `types` folder resolution in typescript.
Migration guide:
- Make sure to set `moduleResolution` to `node16` or `nodenext` for correct module resolution

fix: types export in build artifacts

---

package.json

- fixes statements like `import * from algokit...` in esm based projects
- fixes imports from types or testing folders on node based projects

build: improving typesVersions and exports in package.json

---

docs/capabilities/transaction.md

To fix the other warnings encountered in https://github.com/algorand/docs/pull/1149 we'll need to either:
- Have the `docs` repo detect a TypeScript link and generate an absolute path to this GitHub repo.
- Use absolute paths inside our docs for the TypeScript links.

docs: Remove missing algod type from the docs

---

docs/capabilities/app-client.md
docs/code/modules/index.md
src/__snapshots__/app-deploy.spec.ts.snap
src/transaction.spec.ts
src/transaction.ts
src/types/__snapshots__/app-client.spec.ts.snap
src/types/app-client.spec.ts

After a failed transaction, using simulate to extract more information about what went wrong on a debug mode.

fix: adding simulation on failed transactions

---

package.json

Update min version of algosdk peer dependency to `2.7.0`, as per https://github.com/algorandfoundation/algokit-utils-ts/issues/158

chore: bump algosdk

---

src/app.ts
src/types/app-client.spec.ts

fix: Resolving bug where signer passed in with ABI transaction isn't used for signing

---

.eslintrc
docs/code/classes/types_config.UpdatableConfig.md
docs/code/interfaces/types_config.Config.md
jest.config.ts
package-lock.json
package.json
src/types/config.ts
tests/example-contracts/testing-app/contract.ts

Fixes a `ReferenceError: __dirname is not defined in ES module scope` when using `utils-ts` in an ESM project.
This is a temporary fix to solve the issue, however the longer term solution is to move to something like `rollup` or `tsup` where we can inject shims.

fix: add an isomorphic __dirname implementation

---

docs/code/classes/types_config.UpdatableConfig.md
docs/code/interfaces/types_config.Config.md
src/debugging.ts
src/types/config.ts
src/util.ts

Fix proposal for https://github.com/algorandfoundation/algokit-utils-ts/issues/191
- Adding lazy loading via dynamic import for all uses of node specific modules.
- Tested against algokit react template and a stock next js based project

fix: lazy loading all node specific dependencies

---

README.md

- Documenting a patch for the bug report https://github.com/algorandfoundation/algokit-utils-ts/issues/193
- Readme describes a current workaround for next js specific behaviour in regards to inability to ignore dynamically imported node specific modules in a browser environment. 
- This will no longer be an issue once we integrate with rollup or a similar bundler, which will allow us to exclude/hot-swap debug util helpers with browser compatible stubs https://github.com/algorandfoundation/algokit-utils-ts/issues/188

chore: adding note on next js compatibility

---

docs/code/modules/index.md
src/transaction.ts

Modifies the ATC used for simulate when populating resources to use an empty signer. This avoids users being prompted twice for a signature when using an actual wallet.

fix: transactions signed twice with resource population

---

docs/code/interfaces/types_app.AppCallParams.md
docs/code/interfaces/types_app.AppDeploymentParams.md
docs/code/interfaces/types_app.CreateAppParams.md
docs/code/interfaces/types_app.UpdateAppParams.md
docs/code/interfaces/types_asset.AssetOptInParams.md
docs/code/interfaces/types_asset.AssetOptOutParams.md
docs/code/interfaces/types_transaction.SendTransactionParams.md
docs/code/interfaces/types_transfer.AlgoRekeyParams.md
docs/code/interfaces/types_transfer.AlgoTransferParams.md
docs/code/interfaces/types_transfer.EnsureFundedParams.md
docs/code/interfaces/types_transfer.TransferAssetParams.md
docs/code/modules/index.md
src/transaction.spec.ts
src/transaction.ts
src/types/transaction.ts

Disables resource population by default due to https://github.com/algorand/go-algorand/issues/5914
This is technically a breaking change since it changes the default behavior of atc and appclient calls

feat: disable resource population by default

---

docs/code/modules/index.md
src/transaction.ts
src/types/app-client.spec.ts

Disables resource population in `sendAtomicTransactionComposer`

fix: disable resource population in sendAtomicTransactionComposer

---

docs/code/modules/index.md
src/app-deploy.ts
src/app.ts
src/asset.ts
src/transaction.ts
src/types/__snapshots__/app-client.spec.ts.snap
src/types/app-client.spec.ts
src/types/logic-error.ts
tsconfig.json

Fixes #223 
Unfortunately we can't use the new structured data payload, as it doesn't contain transactionId or the error message, so we need to parse the string anyway.

fix: update logic error parsing to handle the tweaked format from algod

---

.nsprc

- For some reason the ID for [CVE-2023-42282](https://github.com/advisories/GHSA-78xj-cgh5-2h22) changed with npm audit

build: change exception id for npm audit

---

.nsprc
README.md
package-lock.json
package.json
rollup-multi-plugin.ts
rollup.config.ts
tsconfig.json

There was an issue with the rollup config in which only two files:
- src/index.ts
- src/testing/index.ts
were included as input for rollup. Rollup only traced references from these two files to generate the output bundle.
In the types folder, there were exported types that weren't referred to by either of the two inputs. These types weren't bundled into the output.
This PR aims to include all files in the types folder into the bundle output.
- Produced the build output from `main`.
- Added the bundle to an empty git repo and committed.
- Applied the changes from this PR.
- Built and copied the bundle to the above git repo.
- I confirmed that the only changes were:
- Some internal type names.
- The missing types were added.
- I also successfully tested this change with …

fix: export all types in types folder

---

docs/code/classes/types_app_client.ApplicationClient.md
docs/code/classes/types_logic_error.LogicError.md
docs/code/interfaces/types_app_client.AppClientCallABIArgs.md
docs/code/interfaces/types_app_client.AppClientCallCoreParams.md
docs/code/interfaces/types_app_client.AppClientCompilationParams.md
docs/code/interfaces/types_app_client.AppClientDeployCallInterfaceParams.md
docs/code/interfaces/types_app_client.AppClientDeployCoreParams.md
docs/code/interfaces/types_app_client.AppClientDeployParams.md
docs/code/interfaces/types_app_client.AppSourceMaps.md
docs/code/interfaces/types_app_client.FundAppAccountParams.md
docs/code/interfaces/types_app_client.ResolveAppById.md
docs/code/interfaces/types_app_client.ResolveAppByIdBase.md
docs/code/interfaces/types_app_client.SourceMapExport.md
docs/code/interfaces/types_testing.AlgoKitLogCaptureFixture.md
docs/code/interfaces/types_testing.AlgorandFixture.md
docs/code/interfaces/types_testing.AlgorandTestAutomationContext.md
docs/code/modules/types_app_client.md
package-lock.json
src/types/app-client.ts

- Include schema in appclient's create params
Fixes #251

fix: Include schema in AppClient's create params

---

docs/capabilities/asset.md
docs/capabilities/client.md
docs/code/interfaces/types_asset.AssetBulkOptInOutParams.md
docs/code/interfaces/types_asset.AssetOptInParams.md
docs/code/interfaces/types_asset.AssetOptOutParams.md
docs/code/interfaces/types_asset.CreateAssetParams.md
docs/code/interfaces/types_indexer.AssetHolding.md
docs/code/interfaces/types_indexer.AssetTransferTransactionResult.md
docs/code/interfaces/types_indexer.StateProofTransactionResult.md
docs/code/interfaces/types_transaction.SendTransactionParams.md
docs/code/modules/index.md
docs/code/modules/types_asset.md
src/asset.spec.ts
src/asset.ts
src/indexer-lookup.spec.ts
src/network-client.ts
src/types/asset.ts
src/types/indexer.ts

* feat: Added createAsset method
* fix: Updating asset-transfer-transaction.amount and .closeAmount to allow bigint values since they can be 64-bit numbers
BREAKING CHANGE: Indexer's from algokit.getAlgoIndexerClient(...) now have IntDecoding.MIXED rather than IntDecoding.DEFAULT
so that numbers > 53-bit will be accurately represented, you can override this with a new parameter to that function.
Also, a number of fields in types/indexer that can have 64-bit values have been changed from `number` to `number | bigint`.

Added `createAsset` and support 64-bit integers from indexer

---

.github/workflows/release.yml
package-lock.json
package.json

```
❯ npm audit fix --force
npm WARN using --force Recommended protections disabled.
npm WARN audit fix tar@6.2.0 node_modules/npm/node_modules/tar
npm WARN audit fix tar@6.2.0 is a bundled dependency of
npm WARN audit fix tar@6.2.0 npm@9.9.3 at node_modules/npm
npm WARN audit fix tar@6.2.0 It cannot be fixed automatically.
npm WARN audit fix tar@6.2.0 Check for updates to the npm package.
npm WARN audit Updating semantic-release to 23.0.8, which is a SemVer major change.
npm WARN deprecated read-pkg-up@11.0.0: Renamed to read-package-up
```
Change the node version used for semantic-release to v20 since it is the new lowest version required https://github.com/semantic-release/semantic-release/releases/tag/v23.0.0

update semantic release (tar dep) to address CVE-2024-28863

---

docs/code/modules/index.md
src/transaction/transaction.ts

This PR fixes a bug that can ocassionally add an app for a box ref in the wrong transaction. Box refs and the associated app need to be in the same transaction

fix: box resource population

---

docs/code/modules/index.md
src/transaction/transaction.ts

Recent changes made it so that the resource population algorithim looked for a transaction with two resource slots available when adding a box: one for the box, one for the app. 
When adding empty references, however, we don't need an app reference, thus an error will get thrown prematurely if adding an eigth empty box to a transaction. 
This PR makes it so that only 1 slot is needed for empty references

fix: only require one resource slot for empty box refs

---

docs/code/modules/index.md
src/transaction/transaction.spec.ts
src/transaction/transaction.ts

- The initial plan was to wait for upstream algod fix, but multiple users have requested this feature now.  The only downside is increased algod calls, but since resource population is disabled by default I think it is acceptable. 
Won't be long until https://github.com/algorand/go-algorand/pull/5942 is merged and we can remove this code and use the upstream fix.

feat: fix signers during resource population

---

docs/code/classes/types_client_manager.ClientManager.md
docs/code/interfaces/types_client_manager.TypedAppClient.md
docs/code/modules/types_client_manager.md
src/types/client-manager.ts

Using `algorandFixture()` without any supplied config or environment variables was resulting in an undefined indexer config rather than the default localnet config.

fix: adjust logic for resolve config

---

docs/code/modules/testing.md
src/testing/account.ts

Realised I hadn't confirmed the new behaviour when kmd wasn't supplied.
Turns out it throws, which wasn't as per the documented behaviour.
This PR updates the obsoleted `getTestAccount` to have the same behaviour as before.

fix: match the previous getTestAccount behaviour when no kmd client is supplied

---

docs/code/modules/index.md
src/app-deploy.spec.ts
src/app-deploy.ts

- The AVM compresses integers meaning uint64 template variables might have an unknown width when used with `pushint`. This PR allows the given TEAL to use `pushbytes` or `bytes` for uint64 template variables which will preserve the integer width. This will allow PC mapping to stay consistent between initial compile time and deployment. 
For an example of how a compiler might output TEAL, see https://github.com/algorandfoundation/TEALScript/pull/522/files
Assuming no objections, a similar PR will need to be made for py as well

feat: allow bytes substitution for uint64 template vars

---

src/types/app-manager.ts

- Fixes bigint values for template variables when pushbytes is used

fix: bigint template variables

---

docs/capabilities/debugging.md

- Since algosdk sends requests with msgpack format as hardcoded param we need to output it in console as well allowing users to manually get the traces from browser to then debug with avm debug adapter extension

docs: document sourcemap logging with custom event handlers for browser based scenarios

---

docs/code/classes/types_app_client.AppClient.md
docs/code/classes/types_app_client.ApplicationClient.md
docs/code/modules/types_app_client.md
src/types/app-client.spec.ts
src/types/app-client.ts

Add a `clone` method to the AppClient allowing for properties like defaultSender to be overridden.

feat: add support for cloning an app client

---

docs/code/classes/types_account_manager.AccountManager.md
docs/code/classes/types_app_arc56.Arc56Method.md
docs/code/classes/types_composer.default.md
docs/code/interfaces/types_account.AccountConfig.md
docs/code/modules/index.md
docs/code/modules/types_account.md
package-lock.json
package.json
src/account/account.ts
src/transaction/perform-atomic-transaction-composer-simulate.ts
src/transaction/transaction.ts
src/types/account-manager.ts
src/types/account.ts
src/types/composer.ts

Now that 3.26 is on mainnet, we can use `fixSigners` when running a simulate.
This PR also removes the previous workaround.

feta: support fix signers in simulate

---

docs/code/classes/types_app_arc56.Arc56Method.md
docs/code/classes/types_app_client.AppClient.md
docs/code/classes/types_app_client.ApplicationClient.md
docs/code/classes/types_app_factory.AppFactory.md
docs/code/interfaces/types_app_arc56.Arc56Contract.md
docs/code/interfaces/types_app_arc56.Event.md
docs/code/interfaces/types_app_arc56.Method.md
docs/code/interfaces/types_app_arc56.ProgramSourceInfo.md
docs/code/interfaces/types_app_arc56.StorageKey.md
docs/code/interfaces/types_app_arc56.StorageMap.md
docs/code/interfaces/types_app_arc56.StructField.md
docs/code/interfaces/types_app_spec.AppSources.md
docs/code/interfaces/types_app_spec.AppSpec.md
docs/code/interfaces/types_app_spec.CallConfig.md
docs/code/interfaces/types_app_spec.DeclaredSchemaValueSpec.md
docs/code/interfaces/types_app_spec.Hint.md
docs/code/interfaces/types_app_spec.ReservedSchemaValueSpec.md
docs/code/interfaces/types_app_spec.Schema.md
docs/code/interfaces/types_app_spec.SchemaSpec.md
docs/code/interfaces/types_app_spec.StateSchemaSpec.md
docs/code/interfaces/types_app_spec.Struct.md
docs/code/modules/types_app_arc56.md
docs/code/modules/types_app_spec.md
src/types/app-arc56.ts
src/types/app-client.ts
src/types/app-factory-and-client.spec.ts
src/types/app-factory.ts
src/types/app-spec.ts

- Add support for ABI method calls as default values
- Align the ARC56 types to the latest spec
- Add some tsdocs to the newly added clone method

feat: add support for abi methods calls as default values

---

docs/code/classes/types_app_manager.AppManager.md
docs/code/interfaces/types_app_arc56.Arc56Contract.md
src/app-deploy.spec.ts
src/app-deploy.ts
src/types/app-arc56.ts
src/types/app-manager.ts

As part of this PR we've ported over the utils-py code, as it handles a few more scenarios with regards to comment stripping and token replacement and more closely follows ARC47.

fix: prevent base64 in teal from being stripped as a comment

---

README.md
package.json

Convert relative links within the package readme to absolute, so that when the readme is displayed in NPM, the links are valid.
Note: This will require a release so that the NPM package readme is updated.

fix: update NPM readme links

---

docs/code/classes/types_app_manager.AppManager.md
package-lock.json
src/types/app-manager.ts

Resolves #350
Will also backport this to v7

fix: allow passing boxname when getting box value

---

docs/code/modules/types_account.md
src/types/account-manager.spec.ts
src/types/account.ts

algosdk returns this as `authAddr` not `authAddress`.
Resolves #354

fix: correct the account type

---

docs/capabilities/testing.md
docs/code/interfaces/types_testing.AlgoKitLogCaptureFixture.md
docs/code/interfaces/types_testing.AlgorandFixture.md
docs/code/interfaces/types_testing.LogSnapshotConfig.md
docs/code/modules/testing.md
src/app-deploy.spec.ts
src/app.spec.ts
src/indexer-lookup.spec.ts
src/testing/fixtures/algorand-fixture.ts
src/testing/transaction-logger.ts
src/transaction/transaction.spec.ts
src/types/account-manager.spec.ts
src/types/algorand-client.asset.spec.ts
src/types/algorand-client.spec.ts
src/types/algorand-client.transfer.spec.ts
src/types/app-client.spec.ts
src/types/app-factory-and-client.spec.ts
src/types/testing.ts

This makes it clearer in intent and ensured that accounts that are registered are copied across successive contexts.
fix: Resolved bug in transactionLogger.waitForIndexer to only wait for the last transaction, not all logged transactions (which caused problems)

feat: Renamed `algorandFixture`'s `beforeEach` to `newScope`

---

docs/code/classes/types_app_client.AppClient.md
docs/code/classes/types_app_client.ApplicationClient.md
src/types/app-client.ts
src/types/app-factory-and-client.spec.ts

Currently if you pass extra args into an abi call (eg. because you passed `args: [1, 2, 3]` instead of `args: [[1, 2, 3]]` for an array arg) the error you receive is `TypeError: Cannot read properties of undefined (reading 'struct')` as the arg mapping logic attempts to read metadata for an undefined arg.
This PR tweaks the mapping logic to throw a more helpful error when this occurs. The message will instead read something to the effect of `Unexpected arg at position 1. your_method only expects 1 args`

fix: Throw a more helpful error message when a client consumer passes in unexpected args

---

docs/code/classes/types_composer.TransactionComposer.md
src/types/app-client.spec.ts
src/types/composer.ts

Fixes #383
When simulating using `skipSignatures: true` on a  transaction group containing multiple ABI methods, the return values would not be decoded correctly. This was due to an incorrect transaction group index being assigned to the ABI method context used when decoding.

fix: use correct group index for composer.buildTransactions()

---

.github/workflows/check_docs.yml
.github/workflows/pr.yml
.github/workflows/release_to_github.yml
docs/code/classes/types_algo_http_client_with_retry.AlgoHttpClientWithRetry.md
docs/code/classes/types_algokit_core_bridge.TokenHeaderAuthenticationMethod.md
docs/code/classes/types_composer.TransactionComposer.md
docs/code/modules/types_algokit_core_bridge.md
package-lock.json
package.json
src/transaction/transaction.spec.ts
src/types/algokit-core-bridge.ts
src/types/app-client.spec.ts
src/types/app-factory-and-client.spec.ts
src/types/composer.ts

feat: calculate fee with algokit core

---

.github/workflows/prod_release.yml
.github/workflows/release.yml

Uses a dedicated bot token instead of the default GITHUB_TOKEN for merging branches in the release workflow.
This enhances security and allows for better control and auditing of actions performed during the release process.

chore: uses bot token for release workflow

---

.nsprc
docs/code/interfaces/types_app_arc56.Arc56Contract.md
docs/code/interfaces/types_app_arc56.Event.md
docs/code/interfaces/types_app_arc56.Method.md
docs/code/interfaces/types_app_arc56.ProgramSourceInfo.md
docs/code/interfaces/types_app_arc56.StorageKey.md
docs/code/interfaces/types_app_arc56.StorageMap.md
docs/code/interfaces/types_app_arc56.StructField.md
docs/code/modules/index.md
docs/code/modules/types_app_arc56.md
package-lock.json
package.json
src/transaction/transaction.ts
src/types/app-arc56.ts
src/types/app-client.spec.ts
src/util.ts

fix: correct box decoding of uint values < 53 bits
